/* =========================================================
 * ====                   WARNING                        ===
 * =========================================================
 * The code in this tab has been generated from the GUI form
 * designer and care should be taken when editing this file.
 * Only add/edit code inside the event handlers i.e. only
 * use lines between the matching comment tags. e.g.

 void myBtnEvents(GButton button) { //_CODE_:button1:12356:
     // It is safe to enter your event code here  
 } //_CODE_:button1:12356:
 
 * Do not rename this tab!
 * =========================================================
 */

public void Change_Background(GCustomSlider source, GEvent event) { //_CODE_:Background_color:529185:
  //println("Background_color - GCustomSlider >> GEvent." + event + " @ " + millis());
} //_CODE_:Background_color:529185:



// Create all the GUI controls. 
// autogenerated do not edit
public void createGUI(){
  G4P.messagesEnabled(false);
  G4P.setGlobalColorScheme(GCScheme.BLUE_SCHEME);
  G4P.setMouseOverEnabled(false);
  surface.setTitle("Sketch Window");
  Background_color = new GCustomSlider(this, 6, 4, 100, 40, "grey_blue");
  Background_color.setLimits(0.5, 0.0, 255.0);
  Background_color.setNumberFormat(G4P.DECIMAL, 2);
  Background_color.setOpaque(false);
  Background_color.addEventHandler(this, "Change_Background");
}

// Variable declarations 
// autogenerated do not edit
GCustomSlider Background_color; 
